import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Layout from "@/components/Layout";
// import profilePic from "../../public/images/profile/developer-pic-1.png";
import logo from "../../public/images/logo/logo.png";
import AnimatedText from "@/components/AnimatedText";
import Link from "next/link";
import { LinkArrow } from "@/components/Icons";
import HireMe from "@/components/HireMe";
import lightBulb from "../../public/images/svgs/miscellaneous_icons_1.svg";
import Card from "@/components/home/Card";
import CardContainer from "@/components/home/CardContainer";
import OrganizationStructure from "@/components/home/OrganizationStructure";
import AnimatedSubHeading from "@/components/AnimatedSubHeading";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main
        className="flex items-center text-dark w-full min-h-screen dark:text-light
      2xl:
      "
      >
        <Layout className="pt-0 md:p-16 sm:pt-8 md:pt-16">
          <div className="flex items-center justify-between w-full lg:flex-col">
            <div className="w-1/2 md:w-full">
              <Image
                src={logo}
                alt="Mostofa Reza"
                className="w-full h-auto lg:hidden md:inline-block md:w-full"
              />
            </div>
            <div className="w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center ">
              <AnimatedText
                className="!text-6xl !text-left xl:!text-4xl lg:!text-center lg:!text-5xl md:!text-3xl sm:!text-2xl "
                text="Nongor Foundation"
              />
              <p className="my-4 text-base font-medium md:text-sm sm:text-xs">
                "Nongor Foundation" is a non-political, non-profit organization
                aimed at building a prosperous society through mutual
                cooperation and welfare work. They believe social development
                requires organized cooperation and creative thinking to benefit
                future generations.
              </p>
              <div
                className="flex items-center
              self-start mt-2 lg:self-center
              "
              >
                <Link
                  href="/test.pdf"
                  target="_blank"
                  download={true}
                  className="flex items-center 
                  bg-success text-light p-2.5 md:p-1.5 sm:p-1
                  px-6 md:px-4 sm:px-2 md:text-sm sm:text-xs rounded-lg text-lg font-semibold hover:bg-light hover:text-dark 
                  border-2 border-transparent hover:border-dark 
                  hover:underline dark:text-dark dark:bg-light  hover:dark:text-light
                  hover:dark:bg-dark hover:dark:border-light "
                >
                  More info
                  <LinkArrow className="!w-5 ml-1" />
                </Link>
                <Link
                  className="ml-4 text-lg md:text-base sm:text-sm font-medium capitalize text-dark underline dark:text-light"
                  href="mailto:mostofa.reza3@gmail.com"
                  target="_blank"
                >
                  Contact
                </Link>
              </div>
            </div>
          </div>
        </Layout>
      </main>
      <>
        <AnimatedText
          text="Our procedure"
          className="!text-6xl  xl:!text-4xl lg:!text-center lg:!text-5xl md:!text-3xl sm:!text-2xl "
        />
        <AnimatedSubHeading
          className="lg:!text-[1rem] md:!text-[14px] sm:!text-[12px]"
          text="According to the Bangladesh Social Policy, 6 (six) measures will be
          taken to ensure fairness and prosperity in the social system."
        />
        <Layout>
          <CardContainer />
        </Layout>
      </>

      <>
        <AnimatedText
          text="Structure of the organization"
          className="!text-6xl xl:!text-4xl lg:!text-center lg:!text-5xl md:!text-3xl sm:!text-2xl "
        />
        <AnimatedSubHeading
          className="lg:!text-[1rem] md:!text-[14px] sm:!text-[12px]"
          text="Nongor Foundation is a private voluntary organization and will have
          three councils in its organizational structure for the smooth and fair
          management of its functions. (1) General Council, (2) Executive Council and (3) Advisory Council"
        />
        <Layout>
          <OrganizationStructure />
        </Layout>
      </>
    </>
  );
}
